apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: mypvc-aktan
  containers:
  - name: myapp
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: pv-storage