apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-aktan
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv-aktan
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-aktan
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ect4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-aktan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard